# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/MusicPlayer.xdc

# IP: ip/DCM_Audio/DCM_Audio.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DCM_Audio || ORIG_REF_NAME==DCM_Audio} -quiet] -quiet
