# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param synth.incrementalSynthesisCache C:/Users/dell/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-14344-DESKTOP-FE9FEV0/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a200tfbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/vivado/music_player.cache/wt [current_project]
set_property parent.project_path D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/vivado/music_player.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/vivado/music_player.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/AudioInterface.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/beattimer.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/button_process_unit.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/control_player.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/control_reader.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/counter_n.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/countrol_mcu.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/dds.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/dffre.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/ending_change.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/frequency_rom.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/fulladder_n.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/mcu.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/music_player.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/note_player.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/sine_rom.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/song_reader.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/song_rom.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/synch.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/MusicPlayerTop.v
}
read_ip -quiet D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/vivado/music_player.srcs/sources_1/ip/DCM_Audio/DCM_Audio.xci
set_property used_in_implementation false [get_files -all d:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/vivado/music_player.srcs/sources_1/ip/DCM_Audio/DCM_Audio_board.xdc]
set_property used_in_implementation false [get_files -all d:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/vivado/music_player.srcs/sources_1/ip/DCM_Audio/DCM_Audio.xdc]
set_property used_in_implementation false [get_files -all d:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/vivado/music_player.srcs/sources_1/ip/DCM_Audio/DCM_Audio_ooc.xdc]

read_edif D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/AudioInterface.edf
read_edif D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/button_process_unit.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/MusicPlayer.xdc
set_property used_in_implementation false [get_files D:/MyFiles/sophomore2/SystemDesignLab/lab19_MusicPlayer5.17/src/MusicPlayer.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top MusicPLayerTop -part xc7a200tfbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MusicPLayerTop.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MusicPLayerTop_utilization_synth.rpt -pb MusicPLayerTop_utilization_synth.pb"
