# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MyFiles/sophomore2/SystemDesignLab/lab3/vivado/IPCore.srcs/sources_1/ip/PictureROM/PictureROM.xci
# IP: The module: 'PictureROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyFiles/sophomore2/SystemDesignLab/lab3/vivado/IPCore.srcs/sources_1/ip/PictureROM/PictureROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PictureROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/MyFiles/sophomore2/SystemDesignLab/lab3/vivado/IPCore.srcs/sources_1/ip/PictureROM/PictureROM.xci
# IP: The module: 'PictureROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MyFiles/sophomore2/SystemDesignLab/lab3/vivado/IPCore.srcs/sources_1/ip/PictureROM/PictureROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PictureROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
