# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/MyFiles/sophomore2/SystemDesignLab/lab3/vivado/IPCore.cache/wt [current_project]
set_property parent.project_path D:/MyFiles/sophomore2/SystemDesignLab/lab3/vivado/IPCore.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/MyFiles/sophomore2/SystemDesignLab/lab3/vivado/IPCore.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/MyFiles/sophomore2/SystemDesignLab/lab3/fig/fig.coe
read_verilog -library xil_defaultlib {
  D:/MyFiles/sophomore2/SystemDesignLab/lab3/src/TMDSencode.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab3/src/syncGenarator.v
  D:/MyFiles/sophomore2/SystemDesignLab/lab3/src/IPCore.v
}
read_ip -quiet d:/MyFiles/sophomore2/SystemDesignLab/lab3/vivado/IPCore.srcs/sources_1/ip/PictureROM/PictureROM.xci
set_property used_in_implementation false [get_files -all d:/MyFiles/sophomore2/SystemDesignLab/lab3/vivado/IPCore.srcs/sources_1/ip/PictureROM/PictureROM_ooc.xdc]

read_ip -quiet d:/MyFiles/sophomore2/SystemDesignLab/lab3/vivado/IPCore.srcs/sources_1/ip/DCM_PLL/DCM_PLL.xci
set_property used_in_implementation false [get_files -all d:/MyFiles/sophomore2/SystemDesignLab/lab3/vivado/IPCore.srcs/sources_1/ip/DCM_PLL/DCM_PLL_board.xdc]
set_property used_in_implementation false [get_files -all d:/MyFiles/sophomore2/SystemDesignLab/lab3/vivado/IPCore.srcs/sources_1/ip/DCM_PLL/DCM_PLL.xdc]
set_property used_in_implementation false [get_files -all d:/MyFiles/sophomore2/SystemDesignLab/lab3/vivado/IPCore.srcs/sources_1/ip/DCM_PLL/DCM_PLL_ooc.xdc]

read_edif D:/MyFiles/sophomore2/SystemDesignLab/lab3/src/TMDSencode.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/MyFiles/sophomore2/SystemDesignLab/lab3/src/IPCore.xdc
set_property used_in_implementation false [get_files D:/MyFiles/sophomore2/SystemDesignLab/lab3/src/IPCore.xdc]


synth_design -top IPCore -part xc7a200tfbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef IPCore.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file IPCore_utilization_synth.rpt -pb IPCore_utilization_synth.pb"
