set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports LED0]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports start]
set_property PACKAGE_PIN R4 [get_ports clk]
set_property PACKAGE_PIN T14 [get_ports LED0]
set_property PACKAGE_PIN T15 [get_ports LED1]
set_property PACKAGE_PIN B22 [get_ports reset]
set_property PACKAGE_PIN D14 [get_ports start]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]
